/*
 * Language Strings - English Language
 * -=-=-=-=-=-=-ORIGINAL-=-=-=-=-=-=-
 */

// Answers for 8ball command.
module.exports.ballreplies = [
  "Everything is possible.",
  "Without a doubt!",
  "Don't ask me again! I'm a ball!",
  "Outlook not so good.",
  "Yes – definitely.",
  "Come back in 15 years.",
  "My sources say yes.",
  "Leave me alone! I don't know!",
  "Go ask your mother!",
  "Where are my fries? No answer for you!",
  "Probability - 15%.",
  "Yes, of course!",
  "Signs point to yes.",
  "Never!",
  "Try asking Akinator!",
  "Go ask Chuck Norris!",
  "Brilliant idea!",
  "Go ask aliens or something.",
  "Only when the clouds will be green.",
  "Please no questions.",
  "Don't do it.",
  "Go ask Yoda!",
  "Probability - 69%.",
  "Buy me a burger, then I'll tell you.",
  "Give me your real estate, then I'll tell you.",
  "Leave me alone! I'm dancing to hardbass!",
  "Good idea!",
  "No answers right now!",
  "Do I look like prophet? I don't know!",
  "Ask again later! I'll tell you.",
  "I'm thirsty, I'll answer you later.",
  "Reply hazy, try again.",
  "I don't know!",
  "Concentrate and ask again.",
  "Go away! I'm looking at memes!",
  "No",
  "Check back in 5 days. I might tell you.",
  "I don't know, I'm not a genie!",
  "You've got to ask yourself one question: \'Do I feel lucky?\'\nWell, do you?",
  "It is decidedly so.",
  "As I see it, yes.",
  "Not a very good idea.",
  "Come back in 2 years, I'll tell you.",
  "I won't be able to tell you today.",
  "Yes",
  "Do it tommorow!",
  "Very doubtful.",
  "My reply is no.",
  "Possibly.",
  "Go ask Darth Vader!",
  "Go away, It's not my job!",
  "Cannot predict now...",
  "Only when dogs will fly.",
  "Try it! Maybe you'll get lucky.",
  "I think you should do it.",
  "Make them offer they can't refuse.",
  "Outlook good.",
  "Maybe later.",
  "Signs point to no.",
  "OMG, YES!",
  "Most likely.",
  "Better not tell you now.",
  "The stars say no.",
  "Go ask your family.",
  "The stars say yes.",
  "I don't think that's possible.",
  "Probability - 100%.",
  "My sources say no.",
  "Ask me again later.",
  "Maybe someday it will happen.",
  "You may rely on it.",
  "IDK, You tell me.",
  "Do it now!",
  "Probability - 0%.",
  "Why are you asking me this?",
  "I'm not feeling good, ask me a bit later.",
  "I am not sure...",
  "Absolutely!",
  "IDK, Ask someone else.",
  "Leave me alone, I've got a headache!",
  "Go ask Obi-Wan Kenobi!",
  "You can't do that!",
  "Start right now!",
  "Don't try it! You don't have the high ground!",
  "Do it.",
  "Don't count on it.",
  "Never do it.",
  "Are you crazy? Of course not!",
  "JUST DO IT!",
  "It is certain."
];

// Greetings (Translate only first part).
module.exports.greetings = [
  "Greetings from Arabic speaking countries - مرحبا",
  "Greetings from Bengali speaking countries - নমস্কার",
  "Greetings from Bulgarian speaking countries - Здравейте",
  "Greetings from Chinese(Mandarin) speaking countries - 你好",
  "Greetings from Croatian speaking countries - Zdravo",
  "Greetings from Danish speaking countries - Hallo",
  "Greetings from Dutch speaking countries - Hallo",
  "Greetings from Estonian speaking countries - Tere",
  "Greetings from Finnish speaking countries - Moikka",
  "Greetings from French speaking countries - Bonjour",
  "Greetings from German speaking countries - Hallo",
  "Greetings from Greek speaking countries - Γειά σου",
  "Greetings from Hebrew speaking countries - הלו",
  "Greetings from Hindi speaking countries - नमस्ते",
  "Greetings from Hungarian speaking countries - Szevasz",
  "Greetings from Icelandic speaking countries - Halló",
  "Greetings from Indonesian speaking countries - Halo",
  "Greetings from Irish(Gaeilge) speaking countries - Dia dhuit",
  "Greetings from Italian speaking countries - Salve",
  "Greetings from Japanese speaking countries - こんにちは",
  "Greetings from Korean speaking countries - 여보세요",
  "Greetings from Latvian speaking countries - Sveiki",
  "Greetings from Lithuanian speaking countries - Sveiki",
  "Greetings from Luxembourgish speaking countries - Hallo",
  "Greetings from Norwegian speaking countries - Hallo",
  "Greetings from Polish speaking countries - Cześć",
  "Greetings from Portuguese speaking countries - Olá",
  "Greetings from Romanian speaking countries - Bună ziua",
  "Greetings from Russian speaking countries - Привет",
  "Greetings from Slovak speaking countries - Ahoj",
  "Greetings from Spanish speaking countries - Hola",
  "Greetings from Swedish speaking countries - Hallå",
  "Greetings from Thai speaking countries - สวัสดี",
  "Greetings from Turkish speaking countries - Merhaba",
  "Greetings from Vietnamese speaking countries - Xin chào",
  "Greetings from Zulu speaking countries - Sawubona"
];
