/*
 * Language Strings - Latvian Language
 * Translated by: EEHoveckis [19/02/2021]
 */

// Atbildes 8ball komandai.
module.exports.ballreplies = [
  "Viss ir iespējams.",
  "Bez šaubām!",
  "Pārstaj man prasīt! Es esmu bumba!",
  "Iznākums nebūs labs.",
  "Jā, noteikti.",
  "Iegriezies pēc 15 gadiem.",
  "Mani avoti saka jā.",
  "Liec mani mierā! Es nezinu!",
  "Aizej paprasi savai mammai!",
  "Kur ir mani frī kartupeļi? Neko tev neteikšu!",
  "Iespējamība - 15%.",
  "Jā, protams!",
  "Zīmes norāda uz jā.",
  "Nekad!",
  "Mēģini prasīt Akinātoram!",
  "Paprasi Čakam Norisam!",
  "Brīnišķīga ideja!",
  "Paprasi citplanētiešiem vai kādam citam.",
  "Tikai, kad mākoņi būs zaļi.",
  "Lūdzu, bez jautājumies.",
  "Nedari to.",
  "Aizej paprasi Jodai!",
  "Iespējamība - 69%.",
  "Nopērc man burgeru, tad es tev pateikšu.",
  "Atdot man savus īpašumus, tad es tev pateikšu.",
  "Liec mani mierā! Es dejoju pie hardbasa!",
  "Laba ideja!",
  "Šobrīd atbildes nav!",
  "Vai es izskatos pēc pareģa? Es nezinu!",
  "Uzprasi man vēlāk! Tad es tev pateikšu.",
  "Esmu izslāpis, es tev atbildēšu vēlāk.",
  "Atbilde miglaina, mēģini vēlreiz.",
  "Es nezinu!",
  "Koncentrējies un prasi vēlreiz.",
  "Ej prom! Es skatos uz mēmiem!",
  "Nē",
  "Atnāc pēc 5 dienām. Es varbūt tev pateikšu.",
  "Es nezinu, es neesmu džins!",
  "Tev jāuzprasa sev jautājums: \'Vai es jūtos veiksmīgs?\'\nNu, vai tu jūties?",
  "Tas ir neapšaubāmi.",
  "Man izskatās, ka jā.",
  "Ne tik laba ideja.",
  "Atnāc pēc 2 gadiem, tad es tev pateikšu.",
  "To es tev nevarēšu šodien pateikt.",
  "Jā",
  "Dari to rīt!",
  "Diezgan apšaubāmi.",
  "Mana atbilde ir nē.",
  "Iespējams.",
  "Aizej uzprasi Dārtam Vaderam!",
  "Ej prom, tas nav mans darbs!",
  "Nevaru šobrīd paredzēt...",
  "Tikai, kad suņi sāks lidot.",
  "Pamēģini! Varbūt tev paveiksies.",
  "Es domāju tev vajadzētu to darīt.",
  "Veic viņiem piedāvājumu no kura viņi nevarēs atteikties.",
  "Iznākums labs.",
  "Varbūt vēlāk.",
  "Zīmes norāda uz nē.",
  "Ak Dievs! Jā!",
  "Visticamāk ka jā.",
  "Labāk būs tev nezināt.",
  "Zvaigznes saka nē.",
  "Aizej paprasi savai ģimenei.",
  "Zvaigznes saka jā.",
  "Nedomāju, ka tas ir iespējams.",
  "Iespējamība - 100%.",
  "Mani avoti saka nē.",
  "Uzprasi man vēlāk.",
  "Varbūt kādu dienu tas notiks.",
  "Tu vari uz to paļauties.",
  "Es nezinu, pasaki tu man.",
  "Dari to tagad!",
  "Iespējamība - 0%.",
  "Kāpēc tu man to prasi?",
  "Es nejūtos labi, uzprasi man mazliet vēlāk.",
  "Es neesmu pārliecināts...",
  "Protams!",
  "Es nezinu, uzprasi kādam citam.",
  "Liec mani mierā, man sāp galva!",
  "Aizej uzprasi Obi Vanam Kenobi!",
  "Tu to nevari darīt!",
  "Sāc jau tagad!",
  "Nemēģini to darīt! Tu neesi pietiekami augstu!",
  "Dari to.",
  "Nemaz neceri.",
  "Nekad to nedari.",
  "Vai tu esi traks? Protams, ka nē!",
  "DARI TO!",
  "Notekti."
];

// Sveicieni.
module.exports.greetings = [
  "Sveicieni no Arābu valodā runājošām valstīm - مرحبا",
  "Sveicieni no Bengāļu valodā runājošām valstīm - নমস্কার",
  "Sveicieni no Bulgāru valodā runājošām valstīm - Здравейте",
  "Sveicieni no Ķīniešu(Mandarīnu) runājošām valstīm - 你好",
  "Sveicieni no Horvātu valodā runājošām valstīm - Zdravo",
  "Sveicieni no Dāņu valodā runājošām valstīm - Hallo",
  "Sveicieni no Flāmu valodā runājošām valstīm - Hallo",
  "Sveicieni no Igauņu valodā runājošām valstīm - Tere",
  "Sveicieni no Somu valodā runājošām valstīm - Moikka",
  "Sveicieni no Franču valodā runājošām valstīm - Bonjour",
  "Sveicieni no Vācu valodā runājošām valstīm - Hallo",
  "Sveicieni no Grieķu valodās runājošām valstīm - Γειά σου",
  "Sveicieni no Ebreju valodā runājošām valstīm - הלו",
  "Sveicieni no Hindi valodā runājošām valstīm - नमस्ते",
  "Sveicieni no Ungāru runājošām valstīm - Szevasz",
  "Sveicieni no Islandiešu valodā runājošām valstīm - Halló",
  "Sveicieni no Indonēziešu valodā runājošām valstīm - Halo",
  "Sveicieni no Īru(Gaeilge) valodā runājošām valstīm - Dia dhuit",
  "Sveicieni no Itāļu valodā runājošām valstīm - Salve",
  "Sveicieni no Japāņu valodā runājošām valstīm - こんにちは",
  "Sveicieni no Korejiešu valodā runājošām valstīm - 여보세요",
  "Sveicieni no Latviešu valodā runājošām valstīm - Sveiki",
  "Sveicieni no Lietuviešu valodā runājošām valstīm - Sveiki",
  "Sveicieni no Luksemburgiešu valodā runājošām valstīm - Hallo",
  "Sveicieni no Norwēģu valodā runājošām valstīm - Hallo",
  "Sveicieni no Poļu valodā runājošām valstīm - Cześć",
  "Sveicieni no Portugāļu valodā runājošām valstīm - Olá",
  "Sveicieni no Rumāņu valodā runājošām valstīm - Bună ziua",
  "Sveicieni no Krievu valodā runājošām valstīm - Привет",
  "Sveicieni no Slovāku valodā runājošām valstīm - Ahoj",
  "Sveicieni no Spāņu valodā runājošām valstīm - Hola",
  "Sveicieni no Zviedru valodā runājošām valstīm - Hallå",
  "Sveicieni no Thai valodā runājošām valstīm - สวัสดี",
  "Sveicieni no Turku valodā runājošām valstīm - Merhaba",
  "Sveicieni no Vjetnamiešu valodā runājošām valstīm - Xin chào",
  "Sveicieni no Zulu valodā runājošām valstīm - Sawubona"
];
